### ISSUE TITLE
trajopt::InitInfo Does Not Appear to Be Used

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-consortium/trajopt_ros#13]
In all of the examples, we set a `type` variable in the `ProblemConstructionInfo::init_info` struct. E.g.
```c++
pci.init_info.type = trajopt::InitInfo::STATIONARY;
```
This appears to be un-used.

**Comment by mpowelson** [comment]
@Levi-Armstrong This is fixed now as of #50. See generateInitTraj and ConstructProblem. We just need to update the examples next time we are editing them.
