### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/trajopt_ros#187]
For consistency we probably want to update to github actions. Additionally, this uses the legacy branch of industrial_ci. We should update it to use master. Noetic and foxy builds would be nice as well.

- [x] Update to github actions
- [x] Update to industrial CI master branch
- [ ] Add ROS 1 Noetic build
- [ ] Add ROS2 Foxy build

**Comment by Minipada** [comment]
Hi from World ROS-I day

**Comment by gavanderhoorn** [comment]
@Minipada: please note the comment by @mpowelson about using `industrial_ci` for the Github actions.

**Comment by Minipada** [comment]
Thanks for the confirmation, I was taking a look at it

**Comment by Minipada** [comment]
Hi, I first tested making it work with Melodic
short questions:
1. It seems there are circular dependencies. trajopt needs tesseract which needs in return trajopt. I don't see it as an issue but the CI will build it twice, once in the upstream source and once in the workspace. In the ci file, it will translate to having "github:ros-industrial-consortium/trajopt_ros#master" in the `UPSTREAM_WORKSPACE`. If this is fine to you, I'll keep it this way
2. Could you give me a link to the `lharmstrong/tesseract` dockerfiles?

**Comment by mpowelson** [comment]
1) On Tesseract we solve this issue by building both Tesseract and Trajopt in the target workspace. The other packages in the upstream (descartes_light, opw_kinematics, and ifopt) do not need Tesseract, so it shouldn't have to be included twice.

2) I think you should be able to use the dockers being build by ros-industrial/docker now. @Levi-Armstrong 
 merged the Tesseract dockerfiles a few days ago. 

https://hub.docker.com/r/rosindustrial/tesseract/dockerfile

**Comment by Levi-Armstrong** [comment]
This has been completed.
