### ISSUE TITLE
Eliminate need for custom osqp_eigen version

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/trajopt_ros#215]
I don't really remember why this was necessary, but there was an issue with the Xenial build  when using master. As soon as Kinetic is EOL (April 2021) if not before, we need to see if we can switch to using a release version

**Comment by Levi-Armstrong** [comment]
The  feature/CommandLanguage branch will be dropping support for kinetic so if we want to try it on that branch we could.

**Comment by Levi-Armstrong** [comment]
Is this good to close now that we dropped support for Xenial?

**Comment by mpowelson** [comment]
Probably. We'll want to switch it back to use the upstream version.

**Comment by Levi-Armstrong** [comment]
Addressed in PR #257
