### ISSUE TITLE
ERROR wrong number of JointVelTermInfo targets. expected 8 got 0

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial-consortium/trajopt_ros#55]
when I launch car_seat_demo.launch from trajopt_examples , I come across this error and then the launch files crashes. Kindly please help me how to solve this error.

**Comment by mpowelson** [comment]
I probably didn't change this example when I switched the required parameter from coeffs to targets. Targets used to default to all zeros if not given. If you send it a vector of zeros it should work. I'll get that fixed. Thanks.
