### ISSUE TITLE
what():  OGRE EXCEPTION(4:ItemIdentityException): An object of type 'Entity' with name 'Robot Link4' already exists. in SceneManager::createMovableObject at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 6832)

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial-consortium/trajopt_ros#64]
rviz crashes when trying I add tesseracttrajectory with this error.I dont know whats the reason and how I can delete this error.

**Comment by lakshmip001** [comment]
I was able to solve this problem by loading the .rviz configuration file after opening rviz.

**Comment by JeroenDM** [comment]
For future reference. I also got this error when trying to load the `TesseractTrajectory` or `TesseractState` plugin in Rivz. This was resolved by first removing the `MotionPlanning` plugin.

**Comment by Levi-Armstrong** [comment]
Thank you for the feedback. This should be fixed in the upcoming new version. I switched to using Ogre name generaters to insure unique names so it does not clash with the motion planning plugin.
