### ISSUE TITLE
 what():  couldn't find a feasible point. there's probably a problem with variable bounds (e.g. joint limits). wrote to /tmp/fail.lp

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial-consortium/trajopt_ros#85]
create file write callback discarding any of the file's current contents
ERROR couldn't find a feasible point. there's probably a problem with variable bounds (e.g. joint limits). wrote to /tmp/fail.lp
at /home/lakshmi/catkin_ws/src/trajopt_ros/trajopt_sco/src/modeling.cpp:264
terminate called after throwing an instance of 'std::runtime_error'
  what():  couldn't find a feasible point. there's probably a problem with variable bounds (e.g. joint limits). wrote to /tmp/fail.lp
bpmpd_caller: /home/lakshmi/catkin_ws/src/trajopt_ros/trajopt_sco/include/trajopt_sco/bpmpd_io.hpp:35: void bpmpd_io::ser(int, T&, bpmpd_io::SerMode) [with T = char]: Assertion `n == sizeof(T)' failed.
Aborted (core dumped)

sometimes I get this error while running the trajopt . Can  know what I should understand from this and solve this error.

**Comment by mpowelson** [comment]
I'm going to close this. If you are still needing more information or having the issue, feel free to reopen it.
