### ISSUE TITLE
accessing CartPoseTermInfo() after pushing pose_xyz and pose_wxyz

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial-consortium/trajopt_ros#90]
I am able to push pose_xyz and pose_wxyz to the cartposeterminfo() and then I pushed it into problemconstructioninfo() (pci) as shown below.

std::shared_ptr<CartPoseTermInfo> pose_constraint = std::shared_ptr<CartPoseTermInfo>(new CartPoseTermInfo);
    pose_constraint->term_type = TT_CNT;
    pose_constraint->link = ee_link_;
    pose_constraint->timestep = time_step;
    pose_constraint->xyz = pose.translation();

    pose_constraint->wxyz = Vector4d(rotation.w(), rotation.x(), rotation.y(), rotation.z());
    pose_constraint->pos_coeffs = Vector3d(10.0, 10.0, 10.0);
    pose_constraint->rot_coeffs = Vector3d(10.0, 10.0, 10.0);
    pose_constraint->name = "pose_" + std::to_string(time_step);
    pci.cnt_infos.push_back(pose_constraint);
   // std::cout << "pose_xyz" << pose_constraint->xyz << std::endl;
    //std::cout << "pose_wxyz" << pose_constraint->wxyz << std::endl;

I am trying to access data after pushing on which pose_xyz and pose_wxyz is the optimization applied but the pci.cnt_infos is of TermPtr where it doesnt contain pose_xyz and pose_wxyz member variables  while CartTermPtr contains pose_xyz and pose_wxyz member variables. While the base class is TermPtrInfo().

And I would like to know on which /tf frame trajopt is optimizing the path just to check with my fk obtained
nh.param<std::string>("world_frame", world_frame, "world");

from the above parameter shows it takes world as its frame.
Correct me if I am wrong or with respect to which /tf should fk of end_pose should be given

**Comment by mpowelson** [comment]
I'm going to close this. If you are still needing more information or having the issue, feel free to reopen it.
